package com.breno.crushem;

public enum BuildingType
{
	SPARTAN_SOLDIER,
	SPARTAN_DEFENSOR,
	SPARTAN_CHAMPION,
	
	SPARTAN_RED_GUY_FOR_TEST,
	SPARTAN_GREEN_GUY_FOR_TEST,
	SPARTAN_ECONOMY,
	SPARTAN_POPULATION
}
